language: c

git:
  clone: type = push

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y python-ply python-git libelf-dev codespell sparse fakeroot gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - git clone https://github.com/thesofproject/kconfig.git

jobs:
  include:
    - if: type = pull_request
      name: checkpatch
      script:
        - SHA_PR=`git log --oneline -1 | sed -rn "s/.*Merge (.*) into.*/\1/p"`
        - SHA_MAIN=`git log --oneline -1 | sed -rn "s/.*Merge .* into (.*)/\1/p"`
        - scripts/checkpatch.pl --strict --codespell -g $SHA_MAIN..$SHA_PR
    - name: "sparse check"
      script:
        - export ARCH=x86_64
        - make defconfig
        - scripts/kconfig/merge_config.sh .config kconfig/base-defconfig kconfig/sof-defconfig kconfig/hdaudio-codecs-defconfig
        - make modules_prepare
        - make SUBDIRS=sound/soc/sof C=2
    - name: "BUILD SOF Kernel x86_64"
      script:
        - export ARCH=x86_64
        - make defconfig
        - scripts/kconfig/merge_config.sh .config kconfig/base-defconfig kconfig/sof-defconfig
        - make modules_prepare
        - KCFLAGS="-Wall -Werror" make -j`getconf _NPROCESSORS_ONLN` SUBDIRS=sound/soc/sof W=1
        - KCFLAGS="-Wall -Werror" make -j`getconf _NPROCESSORS_ONLN`
        - make bindeb-pkg -j`getconf _NPROCESSORS_ONLN`
    - name: "BUILD SST Kernel x86_64"
      script:
        - export ARCH=x86_64
        - make defconfig
        - scripts/kconfig/merge_config.sh .config kconfig/base-defconfig kconfig/sst-defconfig
        - KCFLAGS="-Wall -Werror" make -j`getconf _NPROCESSORS_ONLN`
